export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REMOVE_ALL_QUESTIONS  = 'REMOVE_ALL_QUESTIONS';
export const CHANGE_QUESTION_NAME  = 'CHANGE_QUESTION_NAME';
export const CHANGE_ANSWER  = 'CHANGE_ANSWER';
<<<<<<< 55fc9591fc1dd6025fd8fd5d3aeaf264f303aace
export const CHANGE_IMAGE  = 'CHANGE_IMAGE';
export const CHANGE_SELECTED_ANSWER = 'CHANGE_SELECTED_ANSWER';
export const CHANGE_QUESTION_DIFFICULTY  = 'CHANGE_QUESTION_DIFFICULTY';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const CHANGE_NAME  = 'CHANGE_NAME';
export const CHANGE_CATEGORY  = 'CHANGE_CATEGORY';
=======
export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
>>>>>>> empty answer field error done
