export const LOAD_CURRENT_MATCH = 'LOAD_CURRENT_MATCH';
export const REMOVE_CURRENT_MATCH = 'REMOVE_CURRENT_MATCH';
export const LOAD_MATCH_DATA = 'LOAD_MATCH_DATA';
export const LOAD_MATCH_DATA_SUCCESS = 'LOAD_MATCH_DATA_SUCCESS';
export const LOAD_MATCH_DATA_FAILURE = 'LOAD_MATCH_DATA_FAILURE';
export const MATCH_NAME_ERROR = 'MATCH_NAME_ERROR';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';

